# Plugins parameters
parameters:
    sayco_sylius_mautic.tracking_host: 'https://example.com'
    sayco_sylius_mautic.api.auth:
        baseUrl: ''
        version: 'BasicAuth'
        userName: ''
        password: ''


# Sylius UI events configuration
sylius_ui:
    events:
        sylius.shop.layout.head:
            blocks:
                sayco_sylius_mautic.tracking_code:
                    template: "@SaycoSyliusMauticPlugin/Shop/SyliusMauticPlugin/tracking_script.html.twig"
                    priority: 100
                    context:
                        tracking_host: '%sayco_sylius_mautic.tracking_host%'
