# Plugins parameters
parameters:
    sayco_sylius_mautic.tracking_config:
        host: 'https://example.com'
        track_outbound: 'true'
        track_mailto: 'true'
        track_tel: 'true'
        track_download: 'true'
        track_download_extensions: [ ".pdf", ".zip", ".doc" ]
    sayco_sylius_mautic.api.auth:
        baseUrl: ''
        version: 'BasicAuth'
        userName: ''
        password: ''


# Sylius UI events configuration
sylius_ui:
    events:
        sylius.shop.layout.head:
            blocks:
                sayco_sylius_mautic.tracking_code:
                    template: "@SaycoSyliusMauticPlugin/Shop/SyliusMauticPlugin/tracking_script.html.twig"
                    priority: 100
                    context:
                        tracking_config: '%sayco_sylius_mautic.tracking_config%'
