services:
    sayco_sylius_mautiuc_plugin.event_listener.address:
        class: Sayco\SyliusMauticPlugin\EventListener\AddressEventsListener
        arguments:
            - '@sayco_sylius_mautic_plugin.http.api.contacts'
            - '@sayco_sylius_mautic_plugin.mapper.contact_data'
        tags:
            - { name: kernel.event_listener, event: sylius.address.post_create, method: onSave }
            - { name: kernel.event_listener, event: sylius.address.post_update, method: onSave }

    sayco_sylius_mautiuc_plugin.event_listener.customer:
        class: Sayco\SyliusMauticPlugin\EventListener\CustomerEventsListener
        arguments:
            - '@sayco_sylius_mautic_plugin.http.api.contacts'
            - '@sayco_sylius_mautic_plugin.mapper.contact_data'
            - '@sylius.repository.address'
        tags:
            - { name: kernel.event_listener, event: sylius.customer.post_create, method: onCreate }
            - { name: kernel.event_listener, event: sylius.customer.post_update, method: onUpdate }
            - { name: kernel.event_listener, event: sylius.customer.post_delete, method: onDelete }
    
    sayco_sylius_mautic_plugin.http.mautic_client:
        class: Sayco\SyliusMauticPlugin\Http\MauticClient
        arguments:
            - '%sayco_sylius_mautic.api.auth%'
            - '@logger'
                
    sayco_sylius_mautic_plugin.http.api.contacts:
        class: Sayco\SyliusMauticPlugin\Http\Api\ContactsApi
        arguments:
            - '@sayco_sylius_mautic_plugin.http.mautic_client'
    
    sayco_sylius_mautic_plugin.mapper.contact_data:
        class: Sayco\SyliusMauticPlugin\Mapper\ContactDataMapper
