services:
    sayco_sylius_mautiuc_plugin.event_listener.customer:
        class: Sayco\SyliusMauticPlugin\EventListener\CustomerEventsListener
        arguments:
            - '@sayco_sylius_mautic_plugin.http.api.contacts'
            - '@sayco_sylius_mautic_plugin.mapper.customer_data'
        tags:
            - { name: kernel.event_listener, event: sylius.customer.post_create, method: onCreate }
            - { name: kernel.event_listener, event: sylius.customer.post_update, method: onUpdate }
            - { name: kernel.event_listener, event: sylius.customer.post_delete, method: onDelete }
    
    sayco_sylius_mautic_plugin.http.mautic_client:
        class: Sayco\SyliusMauticPlugin\Http\MauticClient
        arguments:
            - '%sayco_sylius_mautic.api.auth%'
            - '@logger'
                
    sayco_sylius_mautic_plugin.http.api.contacts:
        class: Sayco\SyliusMauticPlugin\Http\Api\ContactsApi
        arguments:
            - '@sayco_sylius_mautic_plugin.http.mautic_client'
    
    sayco_sylius_mautic_plugin.mapper.customer_data:
        class: Sayco\SyliusMauticPlugin\Mapper\CustomerDataMapper
        arguments:
            - '@sylius.repository.address'
